### ISSUE TITLE
Prepare strategy and template for openwashdata newsletter in separate repo and setup for buttondown format

### ISSUE THREAD

**Issue by larnsce** [openwashdata/book#19]
```[tasklist]
### Tasks
- [ ] Check buttondown markdown possibilities
- [ ] Write up strategy for campaigns and regular, monthly updates
- [ ] Prepare outline template
```

**Comment by larnsce** [comment]
@mianzg: Would you be keen to take this over? Then I would also introduce you to our newsletter system: https://buttondown.email/

You can add this to the bigger roadmap and strategy for the other elements:

- blog
- hackathons
- live streams
- course
- package release cycle
- etc.

**Comment by mianzg** [comment]
Yes, I assigned this to myself.

**Comment by mianzg** [comment]
Set up a newsletter repo and transfer these tasks there. I will close this issue.
