### ISSUE TITLE
define meta data format

### ISSUE THREAD

**Issue by mbannert** [openwashdata/book#2]
- [ ] evaluate feasibility of swissdata style meta information

**Comment by larnsce** [comment]
# Resources

- https://cghlewis.github.io/rladies-nyc-codebook-comparison/#/title-slide
- https://specs.frictionlessdata.io/table-schema/#introduction

**Comment by larnsce** [comment]
Assuming we go down the route of publishing each dataset as an R Package, how well could the swissdata meta information format integrate with the style of `roygen` comments that are used for the documentation package in R Packages?

- context: https://r-pkgs.org/data.html#sec-documenting-data
- exmaple: https://github.com/allisonhorst/palmerpenguins/blob/6dd44e7368129ef05fac921ff03a8d4a426d008c/R/penguins.R

**Comment by larnsce** [comment]
Another great paper that also has a solid section on metadata:

https://arxiv.org/pdf/2002.11626v1.pdf

**Comment by larnsce** [comment]
Could be a useful package: https://cran.r-project.org/web/packages/dataset/index.html

**Comment by larnsce** [comment]
# Notes 2023-02-27

**Idea @mbannert**

- repo with helper package & data repository
- with data repository we can have a prefix and API to link to data repository
- alternative: moderated awesome-list

**Comment by larnsce** [comment]
# Notes 2023-02-27

function for roxygen2 comments in documentation

- function for key-value pair list & title & description
- if there isn't a title and description, but key-value pair, then have reasonable presets

**Comment by larnsce** [comment]
Another element for writing metadata for the packages. I am experimenting with writing the `DESCRIPTION` file manually and then using the `cffr` R Package to write a CITATION.cff file. This file integrates seamlessly with GitHub and Zenodo to show an appropriate citation for the package.

https://docs.ropensci.org/cffr/

**Comment by larnsce** [comment]
I have been diving deeper into the `cffr` R Package. Part of a function that I need: https://github.com/ropensci/cffr/issues/49#issuecomment-1450468797

**Comment by larnsce** [comment]
- [ ] Function to write roxygen2 comments from dictionary.csv
- [ ] Function to write Authors@R in DESCRIPTION from contributors.csv

**Comment by larnsce** [comment]
@mbannert: I have added a label "priority: high". I would like use it, so we have a specific focus during our sprint meetings.

I don't think we need a "medium" or "low" tag, but I want a tag to highlight the tasks that need attention.

**Comment by larnsce** [comment]
I have had a first go at the `roxygen2` comments documentation from a `dictionary.csv` and prepared this function:

https://github.com/openwashdata/openwashdata/blob/main/R/generate_roxygen_docs.R

I have also turned the https://github.com/openwashdata/openwashdata repo into an R package. I have tested this first working version of it.

**Comment by larnsce** [comment]
@mbannert: I am going to close this now. The function for generating roxygen2 comments for the variables is already on the main branch. Scratch it or keep going from there. Adding authors to DESCRIPTION can now be done with usethis.
