### ISSUE TITLE
Design website and prepare content for overview page

### ISSUE THREAD

**Issue by larnsce** [openwashdata/book#3]
This falls under "Activity 1.1: Advertising the opportunities to contribute to the openwashdata community"

```[tasklist]
### Tasks
- [x] Prepare mock-up of website layout
- [x] Write up content for Overview page
- [x] Add Event: Colorado WASH Symposium
- [x] Move Buttondown Newsletter to page on website
- [x] Work through blog post to identify colors and fonts: https://www.emilhvitfeldt.com/post/slidecraft-colors-fonts/
- [x] Write up Tutorial: Hello, GitHub
- [x] Tutorial: Hello, posit Cloud
- [x] Tutorial: Hello, ORCID
- [x] Setup new issue writing a complete Guide / Handbook that has a different purpose than https://github.com/openwashdata/book which is covered in https://github.com/openwashdata/book
- [x] Tutorial: Hello, Element/Matrix/Chat #21
```

**Comment by larnsce** [comment]
# Website layout mock-up

- Overview & index
    - Welcome to openwashdata
    - openwashdata is an international community that applies [[open practices]] to enable data-driven decisions within the greater Water, Sanitation, and Hygiene (WASH) sector
        - Receive credit for work that is not a scientific paper
        - Give recognition to those that support your work
        - Tell stories with data that haven't yet been told 
        - Meet people that care about data being open and reusable
    - Buttons
        - Get Started
        - Newsletter
        - Events
    - Funding
        - Funded by
- Get Started
    - Tutorial: Hello, GitHub
    - Tutorial: Hello, posit Cloud
    - Tutorial: Hello, ORCID
- Events
    - openwashdata community meetup
    - Calendar overview with signup options
- Handbook / Guide
    - A
    - B
    - C
- News
    - Sign-up page for Newsletter
    - Archive for previous newsletters
- Gallery
    - Publications
        - Proposal
    - Media
        - Open Science Interview
    - Data Catalogue
    - Lessons
    - Presentations
    - 
- Blog
    - A
    - B
    - C
- Glossary
    - [[open practices]]
- Help
    - Report a Bug
    - Ask a Question
    - FAQ

**Comment by larnsce** [comment]
@mbannert @mianzg @sebastian-loos 

Here is how I envisioned the structure of the website. How to sign-up for Element could on a "Get Started" page that's front and center or under Handbook / Guide.

The website and structure is mostly inspired by https://quarto.org/

**Comment by larnsce** [comment]
Thank you, @mianzg. I like it a lot. It works as a blog post, but some of the elements could also be pulled out into individual tutorials.

I currently cover the tutorials under the "Get, Started" page. At this point, we probably don't need an additional guide/handbook/tutorials page, but can draw people to the "Get, Started" page and then talk about the different elements in the blog.

Some of your material could be moved here on the "get-started" branch: 

https://github.com/openwashdata/website/blob/get-started/pages/get-started/index.qmd

**Comment by mianzg** [comment]
Yes, my idea is using this as the 1st get-started instead of giving all get-started posts together. This should point people with minimal efforts to get some accounts and connect with us. Otherwise, it would be too many things to sign up and install for very first-comers. I would vision this as a teaser blog, and link to detailed individual blogs which we might explain more terms and practices.
